#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

touch "${CONFIG_DIR}/app/hd-idle.log"
chown hotio:hotio "${CONFIG_DIR}/app/hd-idle.log"

redirect_cmd() {
    if [[ "${DEBUG}" == "yes" ]]; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

# shellcheck disable=SC2086
redirect_cmd exec "${APP_DIR}/usr/sbin/hd-idle" -d -l "${CONFIG_DIR}/app/hd-idle.log" -i "${IDLE_TIME}" ${ARGS}
